### ISSUE TITLE
Recent Installers Fail To Run

### ISSUE THREAD

**Issue by WildByDesign** [Rectify11/Installer#196]
### Description

The v3.0 RC1 from today, including other recent installers from Github Actions all fail to run.

However, if I go back 2 months for example (https://github.com/Rectify11/Installer/actions/runs/5409600584) the installers from that time period do run correctly.

### Steps To Reproduce

Run Rectify11Installer.exe and it fails to run. Seems to be .NET exceptions.

### Rectify11 Version

v3.0 RC1 and other recent

### Windows Version

Windows 11 22H2

### Logs

```
Application: Rectify11Installer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Rectify11Installer.Pages.WelcomePage..ctor()
   at Rectify11Installer.Core.RectifyPages..cctor()

Exception Info: System.TypeInitializationException
   at Rectify11Installer.FrmWizard..ctor()
   at Rectify11Installer.Program.Main(System.String[])
```

```
Faulting application name: Rectify11Installer.exe, version: 3.0.36.0, time stamp: 0x64ca2d54
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2070, time stamp: 0xdf72c80b
Exception code: 0xe0434352
Fault offset: 0x0000000000064c3c
Faulting process id: 0x0x22A4
Faulting application start time: 0x0x1D9C534619AEB43
Faulting application path: D:\Downloads\__rectify11\2023-08-01\Rectify11Installer.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 7fe1c303-499e-4813-a073-0640959d7c68
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by rounk-ctrl** [comment]
i found the issue, working on it

**Comment by rounk-ctrl** [comment]
fixed, will reupload the installer after a while

**Comment by rounk-ctrl** [comment]
done
