### ISSUE TITLE
Installer exits prematurely during "Extracting files" phase

### ISSUE THREAD

**Issue by Thisisauser6443** [Rectify11/Installer#205]
### Description

As the title says, I cannot get any further than the "Extracting files" phase of installation - `C:\Windows\Rectify11` is present, seemingly with all the files required being also being present, and all bundled extras also seem to be fine, as after rebooting, MicaForEveryone launches on startup, similar to how a normal install would work.

### Steps To Reproduce

1. Run the installer, as normal
2. Fill in all the checkboxes, at the selection page
3. Installer just terminates, with no error box or console message

### Rectify11 Version

3.0-RC1 (Also tested with commit 12ad96a, to no avail)

### Windows Version

Windows 11 Pro for Workstations (Beta Insider) - 22H2 22621.1992

### Logs

[installer.log](https://github.com/Rectify11/Installer/files/12270131/installer.log)

_Essentially nothing_

**Comment by legofanlovessayori** [comment]
can be a issue on your side only since when i used the latest commit on my secondary desktop it installed fine

**Comment by Thisisauser6443** [comment]
> can be a issue on your side only since when i used the latest commit on my secondary desktop it installed fine

My thoughts too, considering I just spotted #196, so _maybe_ that's the case
(Though, I'm just recovering from a bricked Windows install, so I **can't** repeat this again xD)

**Comment by rounk-ctrl** [comment]
can you check event viewer

**Comment by Thisisauser6443** [comment]
> can you check event viewer

.NET Runtime
```
Application: Rectify11 - RC1.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at System.Diagnostics.Process.StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
   at System.Diagnostics.Process.Start(System.Diagnostics.ProcessStartInfo)
   at Rectify11Installer.Core.Installer+<InstallShell>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by rounk-ctrl** [comment]
oh

**Comment by rounk-ctrl** [comment]
should be fixed
