### ISSUE TITLE
White background and white text in some places when using dark theme.

### ISSUE THREAD

**Issue by Shockshwat** [Rectify11/Installer#395]
### Description

Some places, specially control panel is unreadable when using dark theme in rectify11. 

### Steps To Reproduce

Open Control panel and go to any setting
![image](https://github.com/Rectify11/Installer/assets/71540383/d0409b56-0fda-4171-93fb-05d8827e7a79)
![image](https://github.com/Rectify11/Installer/assets/71540383/009e8159-218f-4dce-9fdd-5d0de1e684c8)

### Rectify11 Version

V3.1

### Windows Version

Windows 11 22H2

### Logs

No logs needed.

**Comment by komprimiert** [comment]
same issue here

**Comment by jerfer1111** [comment]
Maybe Re-run the installer, or switch the theme to a different one, then the one you set¿

**Comment by ooTruffle** [comment]
make sure shell32.dll.mun gets patched

**Comment by 03302024** [comment]
> make sure shell32.dll.mun gets patched

Can you please explain how?

**Comment by ooTruffle** [comment]
> > make sure shell32.dll.mun gets patched
> 
> Can you please explain how?

Run Installer -> Tick basic icons

**Comment by 03302024** [comment]
> Run Installer -> Tick basic icons

Doing so, I get this error:

icons.reg failed.System.PlatformNotSupportedException: Method requires System.Windows.Forms.
   at Microsoft.VisualBasic.Interaction.InvokeMethod(String methodName, Object[] args)
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11.Phase2.Helper.ImportReg(String path)
backicons.reg failed.System.PlatformNotSupportedException: Method requires System.Windows.Forms.
   at Microsoft.VisualBasic.Interaction.InvokeMethod(String methodName, Object[] args)
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11.Phase2.Helper.ImportReg(String path)
C:\Windows\SystemResources\accessibilitycpl.dll.mun
Final path: C:\Windows\Rectify11\Backup\accessibilitycpl.dll.mun

Press any key to continue...

**Comment by jerfer1111** [comment]
[like]  Jeremy Fernando reacted to your message:
________________________________
