### ISSUE TITLE
error in uninstalling rectify11

### ISSUE THREAD

**Issue by redsora** [Rectify11/Installer#432]
### Description

.

### Steps To Reproduce

just try to uninstall it

### Rectify11 Version

version 3.0

### Windows Version

Windows 11 22H2 beta channel

### Logs

[installer.log](https://github.com/Rectify11/Installer/files/13927549/installer.log)

**Comment by qb20nh** [comment]
```
═════════════════════════════
START: 13-01-2024 02:55:52 PM
Rectify11 Version: 3.1.0.0
═════════════════════════════
Uninstalling themes
───────────────────
Wrote SecureUXHelper.exe
Wrote ThemeDll.dll
Themes.Uninstall() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.Uninstall()

Cleaning up
───────────
Cleanup() succeeded.
══════════════════════════════════════════════

```

**Comment by MishaProductions** [comment]
Exclude c:/windows/rectify11 from your anti virus
