### ISSUE TITLE
Themes install not working

### ISSUE THREAD

**Issue by Aravind-Sathesh** [Rectify11/Installer#444]
### Description

Whenever I tried to install themes from the Rectify11 Installer, it fails with the following error message:

InstallThemes() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()

Deleted old wallpapers.
Deleted themes.
Themes.Install() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()
   at Rectify11Installer.Core.Themes.Install()

### Steps To Reproduce

I'm not exactly sure how to reproduce it, but this may be causing the error:

Install Rectify11
Delete the Rectfy11 folder from C:/Windows
Try to uninstall Rectfy11 using control panel
Retry installing Rectfy11.

### Rectify11 Version

Version 3.1.0.0

### Windows Version

Windows 11 Home 22H2 22621.3007

### Logs

═════════════════════════════
START: 22-01-2024 10:49:04
Rectify11 Version: 3.1.0.0
═════════════════════════════
Preparing Installation
──────────────────────
Wrote 7za.exe
Wrote files.7z
Wrote extras.7z
Wrote ResourceHacker.exe
WriteFiles() succeeded.
C:\WINDOWS\Rectify11\Backup already exists.
Extracting vcredist.exe from extras.7z
Extracting core31.exe from extras.7z
Executing vcredist.exe with arguments /install /quiet /norestart
vcredist.exe exited with error code 1638
Executing core31.exe with arguments /install /quiet /norestart
core31.exe exited with error code 1638
InstallRuntimes() succeeded.
══════════════════════════════════════════════
Installing Themes
─────────────────
Wrote themes.7z
Wrote SecureUXHelper.exe
Wrote ThemeDll.dll
WriteFiles() succeeded.
Extracted files.7z
Deleted old wallpapers.
Copied wallpapers to C:\WINDOWS\web\wallpaper\Rectified
Copied Themetool.
InstallThemes() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()

Deleted old wallpapers.
Deleted themes.
Themes.Install() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()
   at Rectify11Installer.Core.Themes.Install()

Cleaning up
───────────
Cleanup() succeeded.
══════════════════════════════════════════════

**Comment by DasFlogetier** [comment]
I think I had the same issue.
Did you try to deactivate your antivirus during installation?
I did this and the installation was successfull afterwards.

**Comment by zSudoKnight** [comment]
You can also exclude Windows (C:)/WINDOWS/Rectify11 from your Windows Security and the themes will start installing like normal.
