### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by Kirb101** [Rectify11/Installer#535]
### Description

The installation failed. Told me to look here and look at installer.log [installer.log](https://github.com/Rectify11/Installer/files/15285762/installer.log).

### Steps To Reproduce

* Load the installer
* install it
* fail after restore point

### Rectify11 Version

Version 3.0

### Windows Version

Windows 11 23H2 (OS Build 22631.3527)

### Logs

═════════════════════════════
START: 12/05/2024 10:54:07
Rectify11 Version: 3.0.48.0
═════════════════════════════
Preparing Installation
──────────────────────
Wrote 7za.exe
Wrote files.7z
Wrote extras.7z
Wrote ResourceHacker.exe
WriteFiles() succeeded.
C:\Windows\Rectify11\Backup already exists.
Extracting vcredist.exe from extras.7z
Extracting core31.exe from extras.7z
Executing vcredist.exe with arguments /install /quiet /norestart
vcredist.exe exited with error code 1638
Executing core31.exe with arguments /install /quiet /norestart
core31.exe exited with error code 0
InstallRuntimes() succeeded.
══════════════════════════════════════════════
Installing Themes
─────────────────
Wrote themes.7z
Wrote SecureUXHelper.exe
Wrote ThemeDll.dll
WriteFiles() succeeded.
Extracted files.7z
Deleted old wallpapers.
Copied wallpapers to C:\Windows\web\wallpaper\Rectified
Copied Themetool.
InstallThemes() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()

Deleted old wallpapers.
Deleted themes.
Themes.Install() failed. File not found.
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at Rectify11Installer.Core.Themes.InstallThemes()
   at Rectify11Installer.Core.Themes.Install()

Cleaning up
───────────
Cleanup() succeeded.
══════════════════════════════════════════════

**Comment by Kirb101** [comment]
# Never mind.
## I have fixed this.
